#the freeipa container
gitweb:
    hostname: gitweb.example.test
    build: .
    ports:
        - "8082:8082"
    volumes:
        - /tmp/var/lib/git:/var/lib/git:rw
    environment:
        - http_proxy
        - https_proxy
        - ftp_proxy
        - no_proxy
        - GIT_PROJECT_NAME=example
